version: '1.0'

services:
  mysql:
    image: mysql:latest
    container_name: finance-control
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: finance-control
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: